LocalExecutor:
  Bundles:
    - https://pub-1d4d40f0d02c4bd38871ab17542145f6.r2.dev/agnostic-clickhouse-udf_0.0.3_linux_amd64_v3.tar.gz

Clickhouse:
  Settings:
    default_temporary_table_engine: Log
    allow_experimental_dynamic_type: 1
    enable_named_columns_in_function_tuple: 1
    max_execution_time: 300

Batcher:
  MaxBatchSize: 10

TipTracker:
  PollInterval: 60s

Init:
  Setup:
    - create_remote_table.sql

Steps:
  - Stage:
      Files:
        - create_buffer.sql
    Workers: 8

  - Sequencer: {}

  - Stage:
      Files:
        - write_to_sink.sql
        - delete_buffer.sql
