Engine:
  Local:
    Bundles:
      - https://github.com/agnosticeng/agnostic-clickhouse-udf/releases/download/v0.0.10/agnostic-clickhouse-udf_0.0.10_linux_amd64_v3.tar.gz
    Settings:
      default_temporary_table_engine: StripeLog
      max_execution_time: 600
      allow_experimental_json_type: 1
      send_logs_level: warning

Batcher:
  MaxBatchSize: 1000

TipTracker:
  PollInterval: 3600s

Init:
  Setup:
    - create_evm_abi_decoding_dictionary.sql
    - create_source.sql
    - create_sink.sql

Steps:
  - Stage:
      Files:
        - create_buffer.sql
    Workers: 4

  - Sequencer: {}

  - Stage:
      Files:
        - write_to_sink.sql
        - delete_buffer.sql
