Engine:
  Local:
    Bundles:
      - https://github.com/agnosticeng/agnostic-clickhouse-udf/releases/download/v0.0.5/agnostic-clickhouse-udf_0.0.5_linux_amd64_v3.tar.gz
    Settings:
      max_execution_time: 600
      allow_experimental_json_type: 1

Batcher:
  MaxBatchSize: 1000

TipTracker:
  PollInterval: 7200s

Init:
  Setup:
    - create_evm_abi_decoding_dictionary.sql
    - create_source.sql
    - create_sink.sql

Steps:
  - Stage:
      Files:
        - transform.sql
    Workers: 4
