Engine:
  Local:
    Bundles:
      - https://github.com/agnosticeng/agnostic-clickhouse-udf/releases/download/v0.0.10/agnostic-clickhouse-udf_0.0.10_linux_amd64_v3.tar.gz
    Settings:
      default_temporary_table_engine: Log
      allow_experimental_dynamic_type: 1
      enable_named_columns_in_function_tuple: 1
      max_execution_time: 300
      send_logs_level: warning

Batcher:
  MaxBatchSize: 100

TipTracker:
  PollInterval: 60s

Init:
  Setup:
    - create_remote_table.sql

Steps:
  - Stage:
      Files:
        - create_buffer.sql
    Workers: 8

  - Sequencer: {}

  - Stage:
      Files:
        - write_to_sink.sql
        - delete_buffer.sql
