Batcher:
  MaxBatchSize: 1000

TipTracker:
  PollInterval: 60s

Steps:
  - Stage:
      Files:
        - stage_1_1.sql
    Workers: 2

  - Sequencer: {}

  - Stage:
      Files:
        - stage_2_1.sql
        - stage_2_2.sql
