Engine:
  Remote:
    Dsn: 'tcp://localhost:9000/default'
    Settings:
      max_execution_time: 600
      use_hive_partitioning: 1
      remote_filesystem_read_prefetch: false
      output_format_parquet_write_page_index: 1
      output_format_parquet_use_custom_encoder: 1
      
Batcher:
  MaxBatchSize: 1

TipTracker:
  PollInterval: 60s

Steps:
  - Stage:
      Files:
        - transform.sql